from data_collectors.logic.managers.artists_images_gender_manager import ArtistsImagesGenderManager
from data_collectors.logic.managers.billboard_manager import BillboardManager
from data_collectors.logic.managers.genres.genres_artists_origin_manager import GenresArtistsOriginManager
from data_collectors.logic.managers.genres.genres_mapping_manager import GenresMappingManager
from data_collectors.logic.managers.genres.primary_genre_manager import PrimaryGenreManager
from data_collectors.logic.managers.translations.base_translation_manager import BaseTranslationManager
from data_collectors.logic.managers.translations.shazam_israeli_artists_translation_manager import \
    ShazamIsraeliArtistsTranslationManager
from data_collectors.logic.managers.translations.shazam_israeli_tracks_translation_manager import \
    ShazamIsraeliTracksTranslationManager
from data_collectors.logic.managers.translations.spotify_israeli_artists_translation_manager import \
    SpotifyIsraeliArtistsTranslationManager
from data_collectors.logic.managers.missing_ids_managers.genius_missing_ids_manager import GeniusMissingIDsManager
from data_collectors.logic.managers.missing_ids_managers.musixmatch_missing_ids_manager import \
    MusixmatchMissingIDsManager
from data_collectors.logic.managers.missing_ids_managers.shazam_missing_ids_manager import ShazamMissingIDsManager
from data_collectors.logic.managers.radio_snapshots_manager import RadioStationsSnapshotsManager
from data_collectors.logic.managers.shazam.shazam_birth_date_copy_manager import ShazamBirthDateCopyManager
from data_collectors.logic.managers.shazam.shazam_origin_copy_manager import ShazamOriginCopyManager
from data_collectors.logic.managers.shazam.shazam_top_tracks_manager import ShazamTopTracksManager
from data_collectors.logic.managers.tracks_lyrics_manager import TracksLyricsManager
from data_collectors.logic.managers.tracks_lyrics_missing_ids_manager import TracksLyricsMissingIDsManager
from data_collectors.logic.managers.tracks_vectorizer_manager import TracksVectorizerManager
from data_collectors.logic.managers.translations.spotify_israeli_tracks_translation_manager import \
    SpotifyIsraeliTracksTranslationManager
from data_collectors.logic.managers.wikipedia_artists_age_manager import WikipediaArtistsAgeManager
from data_collectors.logic.managers.google import *
from data_collectors.logic.managers.spotify import *
from data_collectors.logic.managers.charts import *
from data_collectors.logic.managers.embeddings import *
