EUROVISION_WIKIPEDIA_PAGE_URL_FORMAT = (
    "https://en.wikipedia.org/wiki/Eurovision_Song_Contest_{year}"
)
EUROVISION_ARTIST_COLUMN = "Artist"
EUROVISION_SONG_COLUMN = "Song"
EUROVISION_POINTS_COLUMN = "Points"
EUROVISION_PLACE_COLUMN = "Place"
EUROVISION_INDEX_COLUMN = "R/O"
EUROVISION_COUNTRY_COLUMN = "Country"
EUROVISION_KEY_COLUMNS = [
    EUROVISION_ARTIST_COLUMN,
    EUROVISION_SONG_COLUMN,
    EUROVISION_PLACE_COLUMN,
    EUROVISION_INDEX_COLUMN,
]
EUROVISION_TABLE_CONTEST_ID_COLUMNS = [
    EUROVISION_ARTIST_COLUMN,
    EUROVISION_SONG_COLUMN,
    EUROVISION_POINTS_COLUMN,
    EUROVISION_PLACE_COLUMN,
]
FIRST_EUROVISION_YEAR = 1957  # Actual contest first year was 1956, but this year was different so currently is ignored
