POSITION_COLUMN_NAME = b'\xd7\x9e\xd7\xa7\xd7\x95\xd7\x9d'.decode("utf-8")
SONG_COLUMN_NAME = b'\xd7\xa9\xd7\x99\xd7\xa8'.decode("utf-8")
ARTIST_COLUMN_NAME = b'\xd7\x91\xd7\x99\xd7\xa6\xd7\x95\xd7\xa2'.decode("utf-8")
PERFORMER_COLUMN_NAME = b'\xd7\x9e\xd7\x91\xd7\xa6\xd7\xa2'.decode("utf-8")
CHART_RELEVANT_COLUMNS = [
    POSITION_COLUMN_NAME,
    SONG_COLUMN_NAME,
    ARTIST_COLUMN_NAME,
    PERFORMER_COLUMN_NAME
]
RADIO_CHART_SHEET_NAME_DATETIME_FORMATS = [
    "%d.%m.%y"
]
EXCLUDED_RADIO_CHARTS_FILES_IDS = [
    '1zJsTgxYkuW6c0TAqVaRI_RMToTTH7gn-',
    '1z8Ys_yQDg3cjhj3uWUaKFVLIk8xB-qmi'
]
EUROVISION_WIKIPEDIA_PAGE_URL_FORMAT = "https://en.wikipedia.org/wiki/Eurovision_Song_Contest_{year}"
EUROVISION_ARTIST_COLUMN = "Artist"
EUROVISION_SONG_COLUMN = "Song"
EUROVISION_POINTS_COLUMN = "Points"
EUROVISION_PLACE_COLUMN = "Place"
EUROVISION_INDEX_COLUMN = "R/O"
EUROVISION_KEY_COLUMNS = [
    EUROVISION_ARTIST_COLUMN,
    EUROVISION_SONG_COLUMN,
    EUROVISION_PLACE_COLUMN,
    EUROVISION_INDEX_COLUMN
]
EUROVISION_TABLE_CONTEST_ID_COLUMNS = [
    EUROVISION_ARTIST_COLUMN,
    EUROVISION_SONG_COLUMN,
    EUROVISION_POINTS_COLUMN,
    EUROVISION_PLACE_COLUMN
]
FIRST_EUROVISION_YEAR = 1957  # Actual contest first year was 1956, but this year was different so currently is ignored
