from data_collectors.logic.collectors.charts import *
from data_collectors.logic.collectors.curations import *
from data_collectors.logic.collectors.genius import *
from data_collectors.logic.collectors.google import *
from data_collectors.logic.collectors.misc import *
from data_collectors.logic.collectors.musixmatch import *
from data_collectors.logic.collectors.openai import *
from data_collectors.logic.collectors.shazam import *
from data_collectors.logic.collectors.spotify import *
from data_collectors.logic.collectors.wikipedia import *
from data_collectors.logic.collectors.misc import *
