[tool.poetry]
name = "data_collectors"
version = "0.1.0"
description = ""
authors = ["nirgodin <70273595+nirgodin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
genie-datastores = {git = "https://github.com/nirgodin/genie-datastores.git", rev = "dda0d28e"}
spotipyio = {git = "https://github.com/nirgodin/spotipyio.git", rev = "79df5f56"}
shazamio = "^0.4.0.1"
asyncio-pool = "^0.6.0"
tqdm = "4.65.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
