[tool.poetry]
name = "data_collectors"
version = "0.1.0"
description = ""
authors = ["nirgodin <70273595+nirgodin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
genie-datastores = {git = "https://github.com/nirgodin/genie-datastores.git", rev = "197b170b", extras = ["postgres", "milvus", "google_drive", "google_sheets"]}
spotipyio = {git = "https://github.com/nirgodin/spotipyio.git", rev = "44f4ebd2"}
shazamio = "^0.4.0.1"
asyncio-pool = "^0.6.0"
tqdm = ">=4.65.0,<5.0"
wikipedia-api = ">0.5,<0.6"
openpyxl = "^3.1.2"
beautifulsoup4 = ">=4.12.2,<4.13"
async-lru = ">=2.0.4,<3.0"
nltk = ">=3.8.1,<4.0"
pytest-playwright = ">=0.4.4,<1.0"
spacy = "3.7.4"
spacy-langdetect = "0.1.2"
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
