[tool.poetry]
name = "data_collectors"
version = "0.1.0"
description = ""
authors = ["nirgodin <70273595+nirgodin@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
genie-datastores = {git = "https://github.com/nirgodin/genie-datastores.git", rev = "3239973a", extras = ["postgres", "milvus", "google_drive", "google_sheets"]}
spotipyio = {git = "https://github.com/nirgodin/spotipyio.git", rev = "4b2e0259"}
shazamio = "^0.4.0.1"
asyncio-pool = "^0.6.0"
tqdm = ">=4.65.0,<5.0"
wikipedia-api = ">0.5,<0.6"
openpyxl = "^3.1.2"
selenium = ">=4.16,<4.17"
beautifulsoup4 = ">=4.12.2,<4.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
